### ISSUE TITLE
Explain widgets bug

### ISSUE THREAD

**Issue by malay-manglish-datasets** [biolab/orange3-explain#68] opened 2023-12-11 14:46 UTC
**What's wrong?**

Explain Model, Explain Prediction and Explain Predictions widgets show error "module numpy has no attribute int".

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system: Windows
- Orange version: 3.36.1.
- How you installed Orange: From web
[data_bike_xai.zip](https://github.com/biolab/orange3/files/13637062/data_bike_xai.zip)
site

**Comment by VesnaT** [comment] 2023-12-15 09:51
I can't reproduce the problem. All three widgets fork fine.
Can you please provide your Orange3-Explain add-on version?

**Comment by PrimozGodec** [comment] 2023-12-15 10:04
There may be a problem with the SHAP library that Orane3-explain uses (some older versions). Can you also provide a library version besides providing an add-on version? You can find those versions by opening the Orange command prompt from the Windows start menu (open the start menu and search for the Orange command prompt). Then run the command `conda list`, and please paste the output to this issue.

**Comment by malay-manglish-datasets** [comment] 2023-12-15 10:12
> I can't reproduce the problem. All three widgets fork fine. Can you please provide your Orange3-Explain add-on version?

0.6.4 < 0.6.8

I have reinstalled Orange, but nothing.

**Comment by malay-manglish-datasets** [comment] 2023-12-15 10:13
> There may be a problem with the SHAP library that Orane3-explain uses (some older versions). Can you also provide a library version besides providing an add-on version? You can find those versions by opening the Orange command prompt from the Windows start menu (open the start menu and search for the Orange command prompt). Then run the command `conda list`, and please paste the output to this issue.

shap                      0.41.0                   pypi_0    pypi

the whole list:
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    <unknown>
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anyio                     4.0.0              pyhd8ed1ab_0    <unknown>
anyqt                     0.2.0              pyh6c4a22f_0    <unknown>
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.4.0              pyhd8ed1ab_0    <unknown>
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0             pyh71513ae_1    <unknown>
backcall                  0.2.0              pyh9f0ad1d_0    <unknown>
backports                 1.0                pyhd8ed1ab_3    <unknown>
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    <unknown>
baycomp                   1.0.2                      py_1    <unknown>
beautifulsoup4            4.12.2                   pypi_0    pypi
biopython                 1.81                     pypi_0    pypi
blas                      2.118                  openblas    <unknown>
blas-devel                3.9.0           18_win64_openblas    <unknown>
bottleneck                1.3.7            py39hc266a54_0    <unknown>
brotli                    1.1.0                hcfcfb64_0    <unknown>
brotli-bin                1.1.0                hcfcfb64_0    <unknown>
brotli-python             1.1.0            py39h99910a6_0    <unknown>
brotlipy                  0.7.0           py39ha55989b_1005    <unknown>
bzip2                     1.0.8                h8ffe710_4    <unknown>
ca-certificates           2023.7.22            h56e8100_0    <unknown>
cachecontrol              0.12.12            pyhd8ed1ab_1    <unknown>
cairo                     1.16.0            hdecc03f_1016    <unknown>
catboost                  1.2.2            py39hcbf5309_0    <unknown>
cattrs                    23.1.2             pyhd8ed1ab_0    <unknown>
certifi                   2023.7.22          pyhd8ed1ab_0    <unknown>
cffi                      1.15.1           py39h68f70e3_2    <unknown>
chardet                   5.2.0            py39hcbf5309_1    <unknown>
charset-normalizer        3.2.0              pyhd8ed1ab_0    <unknown>
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    <unknown>
commonmark                0.9.1                      py_0    <unknown>
conllu                    4.5.3                    pypi_0    pypi
contourpy                 1.1.1            py39h1f6ef14_1    <unknown>
cryptography              38.0.4           py39h58e9bdb_0    <unknown>
cycler                    0.11.0             pyhd8ed1ab_0    <unknown>
cython                    0.29.32                  pypi_0    pypi
debugpy                   1.8.0            py39h99910a6_1    <unknown>
decorator                 5.1.1              pyhd8ed1ab_0    <unknown>
defusedxml                0.7.1                    pypi_0    pypi
dictdiffer                0.9.0              pyhd8ed1ab_0    <unknown>
docutils                  0.20.1           py39hcbf5309_2    <unknown>
docx2txt                  0.8                      pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    <unknown>
et_xmlfile                1.1.0              pyhd8ed1ab_0    <unknown>
exceptiongroup            1.1.3              pyhd8ed1ab_0    <unknown>
executing                 1.2.0              pyhd8ed1ab_0    <unknown>
expat                     2.5.0                h63175ca_1    <unknown>
filelock                  3.8.2              pyhd8ed1ab_0    <unknown>
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    <unknown>
font-ttf-inconsolata      3.000                h77eed37_0    <unknown>
font-ttf-source-code-pro  2.038                h77eed37_0    <unknown>
font-ttf-ubuntu           0.83                 hab24e00_0    <unknown>
fontconfig                2.14.2               hbde0cde_0    <unknown>
fonts-conda-ecosystem     1                             0    <unknown>
fonts-conda-forge         1                             0    <unknown>
fonttools                 4.42.1           py39ha55989b_0    <unknown>
freetype                  2.12.1               hdaf720e_2    <unknown>
fribidi                   1.0.10               h8d14728_0    <unknown>
frozenlist                1.3.3                    pypi_0    pypi
fst-pso                   1.8.1                    pypi_0    pypi
future                    0.18.3             pyhd8ed1ab_0    <unknown>
fuzzytm                   2.0.5                    pypi_0    pypi
gensim                    4.3.0                    pypi_0    pypi
getopt-win32              0.1                  hcfcfb64_1    <unknown>
gettext                   0.21.1               h5728263_0    <unknown>
glib                      2.78.0               h12be248_0    <unknown>
glib-tools                2.78.0               h12be248_0    <unknown>
graphite2                 1.3.13                     1000    <unknown>
graphviz                  8.1.0                h51cb2cd_0    <unknown>
gst-plugins-base          1.22.6               h001b923_1    <unknown>
gstreamer                 1.22.6               hb4038d2_1    <unknown>
gts                       0.7.6                h6b5321d_4    <unknown>
h11                       0.14.0             pyhd8ed1ab_0    <unknown>
h2                        4.1.0            py39hcbf5309_0    <unknown>
harfbuzz                  7.3.0                h196d34a_0    <unknown>
hpack                     4.0.0              pyh9f0ad1d_0    <unknown>
httpcore                  0.18.0             pyhd8ed1ab_0    <unknown>
httpx                     0.24.1                   pypi_0    pypi
hyperframe                6.0.1              pyhd8ed1ab_0    <unknown>
icu                       72.1                 h63175ca_0    <unknown>
idna                      3.4                pyhd8ed1ab_0    <unknown>
importlib-metadata        6.8.0              pyha770c72_0    <unknown>
importlib-resources       6.1.0              pyhd8ed1ab_0    <unknown>
importlib_metadata        6.8.0                hd8ed1ab_0    <unknown>
importlib_resources       6.1.0              pyhd8ed1ab_0    <unknown>
ipykernel                 6.14.0           py39h832f523_0    <unknown>
ipython                   8.4.0            py39hcbf5309_0    <unknown>
ipython_genutils          0.2.0                      py_1    <unknown>
itsdangerous              2.1.2              pyhd8ed1ab_0    <unknown>
jaraco.classes            3.3.0              pyhd8ed1ab_0    <unknown>
jedi                      0.19.0             pyhd8ed1ab_0    <unknown>
jellyfish                 1.0.0                    pypi_0    pypi
joblib                    1.3.2              pyhd8ed1ab_0    <unknown>
jpeg                      9e                   h8ffe710_2    <unknown>
jupyter_client            8.3.1              pyhd8ed1ab_0    <unknown>
jupyter_core              5.3.2            py39hcbf5309_0    <unknown>
keyring                   24.2.0           py39hcbf5309_0    <unknown>
keyrings.alt              4.2.0              pyhd8ed1ab_0    <unknown>
kiwisolver                1.4.5            py39h1f6ef14_1    <unknown>
krb5                      1.20.1               heb0366b_0    <unknown>
langdetect                1.0.9                    pypi_0    pypi
lcms2                     2.15                 h3e3b177_1    <unknown>
lemmagen3                 3.5.0                    pypi_0    pypi
lerc                      4.0.0                h63175ca_0    <unknown>
libblas                   3.9.0           18_win64_openblas    <unknown>
libbrotlicommon           1.1.0                hcfcfb64_0    <unknown>
libbrotlidec              1.1.0                hcfcfb64_0    <unknown>
libbrotlienc              1.1.0                hcfcfb64_0    <unknown>
libcblas                  3.9.0           18_win64_openblas    <unknown>
libclang                  16.0.6          default_heb8d277_1    <unknown>
libclang13                16.0.6          default_hc80b9e7_1    <unknown>
libdeflate                1.18                 hcfcfb64_0    <unknown>
libexpat                  2.5.0                h63175ca_1    <unknown>
libffi                    3.4.2                h8ffe710_5    <unknown>
libflang                  5.0.0           h6538335_20180525    <unknown>
libgd                     2.3.3                h2ed9e1d_6    <unknown>
libglib                   2.78.0               he8f3873_0    <unknown>
libiconv                  1.17                 h8ffe710_0    <unknown>
libjpeg-turbo             2.1.5.1              hcfcfb64_1    <unknown>
liblapack                 3.9.0           18_win64_openblas    <unknown>
liblapacke                3.9.0           18_win64_openblas    <unknown>
libogg                    1.3.4                h8ffe710_1    <unknown>
libopenblas               0.3.24          pthreads_hc140b1d_0    <unknown>
libpng                    1.6.39               h19919ed_0    <unknown>
libsodium                 1.0.18               h8d14728_1    <unknown>
libsqlite                 3.43.0               hcfcfb64_0    <unknown>
libtiff                   4.5.1                h6c8260b_1    <unknown>
libvorbis                 1.3.7                h0e60522_0    <unknown>
libwebp                   1.3.2                hcfcfb64_0    <unknown>
libwebp-base              1.3.2                hcfcfb64_0    <unknown>
libxcb                    1.15                 hcd874cb_0    <unknown>
libxgboost                1.7.6            cpu_h0f92c63_2    <unknown>
libxml2                   2.11.5               hc3477c8_1    <unknown>
libzlib                   1.2.13               hcfcfb64_5    <unknown>
llvm-meta                 5.0.0                         0    <unknown>
llvmlite                  0.40.1                   pypi_0    pypi
lockfile                  0.12.2                     py_1    <unknown>
lttl                      2.0.12                   pypi_0    pypi
lxml                      4.9.2                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    <unknown>
m2w64-gcc-libs            5.3.0                         7    <unknown>
m2w64-gcc-libs-core       5.3.0                         7    <unknown>
m2w64-gmp                 6.1.0                         2    <unknown>
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    <unknown>
matplotlib-base           3.8.0            py39hf19769e_1    <unknown>
matplotlib-inline         0.1.6              pyhd8ed1ab_0    <unknown>
miniful                   0.0.6                    pypi_0    pypi
more-itertools            10.1.0             pyhd8ed1ab_0    <unknown>
msgpack-python            1.0.4            py39h1f6ef14_1    <unknown>
msys2-conda-epoch         20160418                      1    <unknown>
multidict                 6.0.4                    pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    <unknown>
ndf                       0.1.4                    pypi_0    pypi
nest-asyncio              1.5.6              pyhd8ed1ab_0    <unknown>
networkx                  3.1                pyhd8ed1ab_0    <unknown>
nltk                      3.8.1                    pypi_0    pypi
numba                     0.57.1                   pypi_0    pypi
numpy                     1.24.4           py39h816b6a6_0    <unknown>
oauthlib                  3.2.2                    pypi_0    pypi
odfpy                     1.4.1                    pypi_0    pypi
openai                    0.27.8                   pypi_0    pypi
openblas                  0.3.24          pthreads_h3721920_0    <unknown>
openjpeg                  2.5.0                ha2aaf27_2    <unknown>
openmp                    5.0.0                    vc14_1  [vc14]  <unknown>
openpyxl                  3.1.2            py39ha55989b_1    <unknown>
openssl                   3.1.3                hcfcfb64_0    <unknown>
opentsne                  1.0.0            py39h6d95a06_0    <unknown>
orange-canvas-core        0.1.31                   pypi_0    pypi
orange-widget-base        4.21.0                   pypi_0    pypi
orange3                   3.36.1           py39h32e6231_0    <unknown>
orange3-associate         1.2.0                    pypi_0    pypi
orange3-explain           0.6.4                    pypi_0    pypi
orange3-imageanalytics    0.11.0                   pypi_0    pypi
orange3-network           1.7.0                    pypi_0    pypi
orange3-prototypes        0.19.0                   pypi_0    pypi
orange3-text              1.13.1                   pypi_0    pypi
orange3-textable          3.1.11                   pypi_0    pypi
orange3-timeseries        0.5.3                    pypi_0    pypi
owlready2                 0.43                     pypi_0    pypi
packaging                 23.1               pyhd8ed1ab_0    <unknown>
pandas                    1.5.3            py39h2ba5b7c_1    <unknown>
pandas-datareader         0.10.0                   pypi_0    pypi
pango                     1.50.14              hd64ce24_1    <unknown>
parso                     0.8.3              pyhd8ed1ab_0    <unknown>
patsy                     0.5.3                    pypi_0    pypi
pcre2                     10.40                h17e33f8_0    <unknown>
pdfminer3k                1.3.4                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    <unknown>
pillow                    10.0.0           py39ha9166d5_0    <unknown>
pip                       23.2.1             pyhd8ed1ab_0    <unknown>
pixman                    0.42.2               h63175ca_0    <unknown>
platformdirs              3.10.0             pyhd8ed1ab_0    <unknown>
plotly                    5.17.0             pyhd8ed1ab_0    <unknown>
ply                       3.11                       py_1    <unknown>
pooch                     1.7.0              pyha770c72_3    <unknown>
prompt-toolkit            3.0.39             pyha770c72_0    <unknown>
psutil                    5.9.5            py39ha55989b_1    <unknown>
pthread-stubs             0.4               hcd874cb_1001    <unknown>
pure_eval                 0.2.2              pyhd8ed1ab_0    <unknown>
py-xgboost                1.7.6           cpu_py39h7090721_2    <unknown>
pybind11                  2.10.4                   pypi_0    pypi
pyclipper                 1.3.0.post4              pypi_0    pypi
pycountry                 22.3.5                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    <unknown>
pyfume                    0.2.25                   pypi_0    pypi
pygments                  2.16.1             pyhd8ed1ab_0    <unknown>
pyopenssl                 22.1.0             pyhd8ed1ab_0    <unknown>
pyparsing                 3.1.1              pyhd8ed1ab_0    <unknown>
pyqt                      5.15.9           py39hb77abff_5    <unknown>
pyqt5-sip                 12.12.2          py39h99910a6_5    <unknown>
pyqtgraph                 0.13.3             pyhd8ed1ab_0    <unknown>
pyqtwebengine             5.15.9           py39h2f4a3f1_5    <unknown>
pysocks                   1.7.1            py39hcbf5309_5    <unknown>
python                    3.9.12          hcf16a7b_1_cpython    <unknown>
python-dateutil           2.8.2              pyhd8ed1ab_0    <unknown>
python-graphviz           0.20.1             pyh22cad53_0    <unknown>
python-louvain            0.16               pyhd8ed1ab_0    <unknown>
python_abi                3.9                      4_cp39    <unknown>
pytz                      2023.3.post1       pyhd8ed1ab_0    <unknown>
pywin32                   306              py39h99910a6_1    <unknown>
pywin32-ctypes            0.2.2            py39hcbf5309_1    <unknown>
pyyaml                    6.0.1            py39ha55989b_1    <unknown>
pyzmq                     25.1.1           py39hea35a22_1    <unknown>
qasync                    0.24.2             pyh9208f05_0    <unknown>
qt-main                   5.15.8              h2c8576c_12    <unknown>
qt-webengine              5.15.8               h5b1ea0b_0    <unknown>
qtconsole                 5.4.4              pyhd8ed1ab_0    <unknown>
qtconsole-base            5.4.4              pyha770c72_0    <unknown>
qtpy                      2.4.0              pyhd8ed1ab_0    <unknown>
regex                     2023.6.3                 pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    <unknown>
requests-cache            1.1.0              pyhd8ed1ab_0    <unknown>
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3986                   1.5.0              pyhd8ed1ab_0    <unknown>
scikit-learn              1.1.3            py39h6fe01c0_1    <unknown>
scipy                     1.10.1           py39hde5eda1_3    <unknown>
segtok                    1.5.11                   pypi_0    pypi
serverfiles               0.3.0                      py_0    <unknown>
setuptools                68.2.2             pyhd8ed1ab_0    <unknown>
shap                      0.41.0                   pypi_0    pypi
simhash                   2.1.2                    pypi_0    pypi
simpful                   2.11.0                   pypi_0    pypi
sip                       6.7.11           py39h99910a6_1    <unknown>
six                       1.16.0             pyh6c4a22f_0    <unknown>
slicer                    0.0.7                    pypi_0    pypi
smart-open                6.3.0                    pypi_0    pypi
sniffio                   1.3.0              pyhd8ed1ab_0    <unknown>
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.43.0               hcfcfb64_0    <unknown>
stack_data                0.6.2              pyhd8ed1ab_0    <unknown>
statsmodels               0.14.0                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  8.2.3              pyhd8ed1ab_0    <unknown>
threadpoolctl             3.2.0              pyha21a80b_0    <unknown>
tiktoken                  0.4.0                    pypi_0    pypi
tk                        8.6.13               hcfcfb64_0    <unknown>
toml                      0.10.2             pyhd8ed1ab_0    <unknown>
tomli                     2.0.1              pyhd8ed1ab_0    <unknown>
tornado                   6.3.3            py39ha55989b_1    <unknown>
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.10.1             pyhd8ed1ab_0    <unknown>
treetaggerwrapper         2.3                      pypi_0    pypi
tweepy                    4.14.0                   pypi_0    pypi
typing-extensions         4.8.0                hd8ed1ab_0    <unknown>
typing_extensions         4.8.0              pyha770c72_0    <unknown>
tzdata                    2023c                h71feb2d_0    <unknown>
ucrt                      10.0.22621.0         h57928b3_0    <unknown>
ufal-udpipe               1.3.0.1                  pypi_0    pypi
ujson                     5.8.0            py39h99910a6_0    <unknown>
unicodedata2              15.1.0           py39ha55989b_0    <unknown>
url-normalize             1.4.3              pyhd8ed1ab_0    <unknown>
urllib3                   2.0.5              pyhd8ed1ab_0    <unknown>
vc                        14.3                h64f974e_17    <unknown>
vc14_runtime              14.36.32532         hdcecf7f_17    <unknown>
vs2015_runtime            14.36.32532         h05e6639_17    <unknown>
wcwidth                   0.2.6              pyhd8ed1ab_0    <unknown>
wheel                     0.41.2             pyhd8ed1ab_0    <unknown>
wikipedia                 1.4.0                    pypi_0    pypi
win_inet_pton             1.1.0            py39hcbf5309_5    <unknown>
xgboost                   1.7.6           cpu_py39h7090721_2    <unknown>
xlrd                      2.0.1              pyhd8ed1ab_3    <unknown>
xlsxwriter                3.1.5              pyhd8ed1ab_0    <unknown>
xorg-kbproto              1.0.7             hcd874cb_1002    <unknown>
xorg-libice               1.1.1                hcd874cb_0    <unknown>
xorg-libsm                1.2.4                hcd874cb_0    <unknown>
xorg-libx11               1.8.6                hefa74cf_0    <unknown>
xorg-libxau               1.0.11               hcd874cb_0    <unknown>
xorg-libxdmcp             1.1.3                hcd874cb_0    <unknown>
xorg-libxext              1.3.4                hcd874cb_2    <unknown>
xorg-libxpm               3.5.16               hcd874cb_0    <unknown>
xorg-libxt                1.3.0                hcd874cb_1    <unknown>
xorg-xextproto            7.3.0             hcd874cb_1003    <unknown>
xorg-xproto               7.0.31            hcd874cb_1007    <unknown>
xz                        5.2.6                h8d14728_0    <unknown>
yake                      0.4.8                    pypi_0    pypi
yaml                      0.2.5                h8ffe710_2    <unknown>
yarl                      1.9.2                    pypi_0    pypi
zeromq                    4.3.4                h0e60522_1    <unknown>
zipp                      3.17.0             pyhd8ed1ab_0    <unknown>
zlib                      1.2.13               hcfcfb64_5    <unknown>
zstd                      1.5.5                h12be248_0    <unknown>

**Comment by PrimozGodec** [comment] 2023-12-15 10:19
It may be connected to https://github.com/shap/shap/issues/3055.

~Can you run `pip install -U shap` in the same Orange command prompt you used to get versions?~

We found out that a newer version of ornage3-explain requires a newer version of SHAP so maybe it is better to just upgrade the explain addon in Orange addon dialog.

Let us know if it solves the problem.

**Comment by malay-manglish-datasets** [comment] 2023-12-15 11:49
> It may be connected to [shap/shap#3055](https://github.com/shap/shap/issues/3055).
> 
> ~Can you run `pip install -U shap` in the same Orange command prompt you used to get versions?~
> 
> We found out that a newer version of ornage3-explain requires a newer version of SHAP so maybe it is better to just upgrade the explain addon in Orange addon dialog.
> 
> Let us know if it solves the problem.

I ran the pip and now its working fine though it showed the below notification.

(C:\Orange) C:\Orange>pip install -U shap
Requirement already satisfied: shap in c:\users\rui\appdata\roaming\python\python39\site-packages (0.43.0)
Collecting shap
  Obtaining dependency information for shap from https://files.pythonhosted.org/packages/a4/69/d7fa1ed3a315d3e63f4d57f6c9e4523fba4f179fb5fd1dee6b2085491195/shap-0.44.0-cp39-cp39-win_amd64.whl.metadata
  Downloading shap-0.44.0-cp39-cp39-win_amd64.whl.metadata (24 kB)
Requirement already satisfied: numpy in c:\users\rui\appdata\roaming\python\python39\site-packages (from shap) (1.21.6)
Requirement already satisfied: scipy in c:\users\rui\appdata\roaming\python\python39\site-packages (from shap) (1.10.1)
Requirement already satisfied: scikit-learn in c:\users\rui\appdata\roaming\python\python39\site-packages (from shap) (1.2.2)
Requirement already satisfied: pandas in c:\orange\lib\site-packages (from shap) (1.5.3)
Requirement already satisfied: tqdm>=4.27.0 in c:\orange\lib\site-packages (from shap) (4.65.0)
Requirement already satisfied: packaging>20.9 in c:\orange\lib\site-packages (from shap) (23.1)
Requirement already satisfied: slicer==0.0.7 in c:\users\rui\appdata\roaming\python\python39\site-packages (from shap) (0.0.7)
Requirement already satisfied: numba in c:\orange\lib\site-packages (from shap) (0.57.1)
Requirement already satisfied: cloudpickle in c:\orange\lib\site-packages (from shap) (2.2.1)
Requirement already satisfied: colorama in c:\orange\lib\site-packages (from tqdm>=4.27.0->shap) (0.4.6)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\orange\lib\site-packages (from numba->shap) (0.40.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\orange\lib\site-packages (from pandas->shap) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\orange\lib\site-packages (from pandas->shap) (2023.3.post1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\rui\appdata\roaming\python\python39\site-packages (from scikit-learn->shap) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\orange\lib\site-packages (from scikit-learn->shap) (3.2.0)
Requirement already satisfied: six>=1.5 in c:\orange\lib\site-packages (from python-dateutil>=2.8.1->pandas->shap) (1.16.0)
Downloading shap-0.44.0-cp39-cp39-win_amd64.whl (447 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 448.0/448.0 kB 5.6 MB/s eta 0:00:00
Installing collected packages: shap
  Attempting uninstall: shap
    Found existing installation: shap 0.43.0
    Uninstalling shap-0.43.0:
      Successfully uninstalled shap-0.43.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
orange3-explain 0.6.4 requires shap==0.41.*, but you have shap 0.44.0 which is incompatible.
Successfully installed shap-0.41.0

**Comment by malay-manglish-datasets** [comment] 2023-12-15 11:51
> > It may be connected to [shap/shap#3055](https://github.com/shap/shap/issues/3055).
> > ~Can you run `pip install -U shap` in the same Orange command prompt you used to get versions?~
> > We found out that a newer version of ornage3-explain requires a newer version of SHAP so maybe it is better to just upgrade the explain addon in Orange addon dialog.
> > Let us know if it solves the problem.
> 
> I ran the pip and now its working fine though it showed the below notification.
> 
> (C:\Orange) C:\Orange>pip install -U shap Requirement already satisfied: shap in c:\users\rui\appdata\roaming\python\python39\site-packages (0.43.0) Collecting shap Obtaining dependency information for shap from https://files.pythonhosted.org/packages/a4/69/d7fa1ed3a315d3e63f4d57f6c9e4523fba4f179fb5fd1dee6b2085491195/shap-0.44.0-cp39-cp39-win_amd64.whl.metadata Downloading shap-0.44.0-cp39-cp39-win_amd64.whl.metadata (24 kB) Requirement already satisfied: numpy in c:\users\rui\appdata\roaming\python\python39\site-packages (from shap) (1.21.6) Requirement already satisfied: scipy in c:\users\rui\appdata\roaming\python\python39\site-packages (from shap) (1.10.1) Requirement already satisfied: scikit-learn in c:\users\rui\appdata\roaming\python\python39\site-packages (from shap) (1.2.2) Requirement already satisfied: pandas in c:\orange\lib\site-packages (from shap) (1.5.3) Requirement already satisfied: tqdm>=4.27.0 in c:\orange\lib\site-packages (from shap) (4.65.0) Requirement already satisfied: packaging>20.9 in c:\orange\lib\site-packages (from shap) (23.1) Requirement already satisfied: slicer==0.0.7 in c:\users\rui\appdata\roaming\python\python39\site-packages (from shap) (0.0.7) Requirement already satisfied: numba in c:\orange\lib\site-packages (from shap) (0.57.1) Requirement already satisfied: cloudpickle in c:\orange\lib\site-packages (from shap) (2.2.1) Requirement already satisfied: colorama in c:\orange\lib\site-packages (from tqdm>=4.27.0->shap) (0.4.6) Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\orange\lib\site-packages (from numba->shap) (0.40.1) Requirement already satisfied: python-dateutil>=2.8.1 in c:\orange\lib\site-packages (from pandas->shap) (2.8.2) Requirement already satisfied: pytz>=2020.1 in c:\orange\lib\site-packages (from pandas->shap) (2023.3.post1) Requirement already satisfied: joblib>=1.1.1 in c:\users\rui\appdata\roaming\python\python39\site-packages (from scikit-learn->shap) (1.3.2) Requirement already satisfied: threadpoolctl>=2.0.0 in c:\orange\lib\site-packages (from scikit-learn->shap) (3.2.0) Requirement already satisfied: six>=1.5 in c:\orange\lib\site-packages (from python-dateutil>=2.8.1->pandas->shap) (1.16.0) Downloading shap-0.44.0-cp39-cp39-win_amd64.whl (447 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 448.0/448.0 kB 5.6 MB/s eta 0:00:00 Installing collected packages: shap Attempting uninstall: shap Found existing installation: shap 0.43.0 Uninstalling shap-0.43.0: Successfully uninstalled shap-0.43.0 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. orange3-explain 0.6.4 requires shap==0.41.*, but you have shap 0.44.0 which is incompatible. Successfully installed shap-0.41.0

Opps i accidentally sent before finishing.

I actually reinstalled the whole Orange plus the add ons updates but didn't work. the -U works. Thanks a lot everyone.

**Comment by PrimozGodec** [comment] 2023-12-15 12:00
Thanks for trying.

The warning you get is because you have an older version of orange3-explain installed, and it requires an older version of SHAP however, there is a newer version of Explain add-on available, and you can update it from the Add-ons menu in Orange. 

The newer version of Explain already requires a newer version of SHAP so the problem is already solved on our side, and therefore, I am closing this issue.

**Closed as completed by PrimozGodec** 2023-12-15 12:00 UTC
Labels: bug report
