### ISSUE TITLE
Explain Predictions: Small discrepancies between base value and average probability

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-explain#32] opened 2021-06-18 14:58 UTC
Assuming I understand the widget and SHAP values correctly, the "Base value" should be the average probability for the given class value. In reality, this is not the case.

Example. I use heart-disease data and Logistic Regression. Then I predict the first instance in the data set. This is the result of Explain Predictions.

<img width="714" alt="Screen Shot 2021-06-18 at 16 53 35" src="https://user-images.githubusercontent.com/12524972/122580276-113e6a00-d056-11eb-82d3-f61d45372c01.png">

Base value is supposed to be 0.47. I now check this in the Box Plot. I use the same model with Predictions and pass the same "Background Data". Then I use Box Plot to observe the probabilities for a given class value, in this case, the Logistic Regression (1). This is the result.

<img width="827" alt="Screen Shot 2021-06-18 at 16 53 47" src="https://user-images.githubusercontent.com/12524972/122580443-434fcc00-d056-11eb-8764-a072949b865e.png">

The mean of Logistic Regression predictions in Box Plot is 0.458. Explain Predictions reports base value as 0.474. Why the difference?

Versions:
shap==0.37.0
Shapely==1.7.1

**Comment by matejklemen** [comment] 2021-11-20 20:46
You are correct that the base value should be the average (or rather expected) probability. SHAP however does not compute this on _all_ reference data (because it could be very slow) but instead computes it on _centroids_ of clustered reference data. So TL;DR, the base value is an approximation.

In your concrete case, you provide 303 instances as original reference data, which get clustered into 10 clusters (k=10 set in `_explain_other_models`). The 10 centroids are passed through the model and the expected value is calculated based on these predictions, weighted by the proportion of original reference instances which fall into each cluster.

**Comment by PrimozGodec** [comment] 2022-01-21 11:18
As @matejklemen said it is an approximation that is in all cases very close to the actual base value. Here the solution could be to calculate our own base value (to make predictions and then average them), but I do not know if it is really necessary. 

@ajdapretnar, do you have a case where it would be necessary to have an exact base value? Maybe we can just add information that is an approximation in the documentation.

**Comment by ajdapretnar** [comment] 2022-01-21 12:01
@PrimozGodec My naive interpretation is class distribution (i.e. 33% for iris setosa) and mean (i.e. 22.533 for housing).

But I assume this is not what is meant by "base value".

**Comment by Btibert3** [comment] 2022-03-23 16:04
I was about to log this and see that there is active discussion.  I replicated the example code from the python library shap, and then exported the data to Orange.  Subtle difference on the reported base value in Orange as discussed above, but spot on if I only used the python library.

**Comment by PrimozGodec** [comment] 2023-08-21 10:49
Closing since it is expected behaviour.

**Closed as completed by PrimozGodec** 2023-08-21 10:49 UTC
